steps:
  - label: ":docker: Build"
    agents:
      queue: hosted-amd64-small
    command: docker buildx bake dev

  - label: ":golang: Test"
    image: golang:1.25.5@sha256:a22b2e6c5e753345b9759fba9e5c1731ebe28af506745e98f406cc85d50c828e
    command: ".buildkite/steps/test"

  - label: ":helm: Lint Chart"
    command: ".buildkite/steps/lint-chart"

  - block: ":rocket: Release"
    if: build.branch == "main"
    prompt: "Create a new release?"

  - label: ":pipeline: Upload release pipeline"
    if: build.branch == "main"
    command: buildkite-agent pipeline upload .buildkite/pipeline.release.yml
